### PR TITLE
License Activation Error Notice

### LINKED ISSUE #3042: Update EDD Software Licensing Implementation
Our licensing API returns 'failed' rather than the API error itself. This needs to be updated.

### PR DESCRIPTION
**Pull request by kstover**
Adding a notice to the settings screen when a license activation error occurs and the nf_debug querystring is set to 1. Closes #3042.

I had to update the Notices.php file because it was returning early when there was an issue while looping over admin notices instead of continuing. This made it impossible to fire later notices when an early one should have been skipped.

I also added a flag for admin notices called "ignore_spam" which tells the admin notice class you want the notice to display, regardless of how many Ninja Forms notices there are on the screen.

### CODE REVIEW

File: includes/Admin/Notices.php [hunk 1]
```diff
@@ -138,6 +146,8 @@ public function admin_notice( $admin_notices ) {
                 }
             }
         }
+
+        // die( 'done looping' );
```
Comment (kjohnson) [inline includes/Admin/Notices.php]: Stray comment.

File: includes/Admin/Notices.php [hunk 2]
```diff
@@ -74,10 +80,12 @@ public function admin_notice( $admin_notices ) {
                 if( ( isset( $admin_notices[ $slug ][ 'blacklist' ] ) && $this->admin_notice_pages_blacklist( $admin_notices[ $slug ][ 'blacklist' ] ) )
                     || ( isset( $admin_notices[ $slug ][ 'pages' ] ) && ! $this->admin_notice_pages( $admin_notices[ $slug ][ 'pages' ] ) )
                 ) {
-                    return false;
+                    continue;
                 }
             }
 
+            
+
```
Comment (kjohnson) [inline includes/Admin/Notices.php]: Extra spacing?

**Comment by kjohnson** [comment]
Closes #3057 .
