### PR TITLE
Remove unecessary admin queries

### LINKED ISSUE #3311: Admin pages loading slowly with lots of post data
On a site with increased amounts of posts, there is a clear difference in admin page load time with Ninja Forms enabled vs. disabled.

You'll need an installation with roughly 100k posts to reproduce a drastic enough time-lag to be noticeable.

### PR DESCRIPTION
**Pull request by kjohnson**
- Add admin page check before initializing Terms field setting (for the builder).

Fixes #3311

### CODE REVIEW

File: ninja-forms.php [hunk 1]
```diff
@@ -399,14 +399,15 @@ public function scrub_available_actions( $actions )
 
         public function admin_notices()
         {
+            if( empty( $_GET[ 'page' ] ) || 'ninja-forms' !== $_GET[ 'page' ] ) return;
```
Comment (Much2tall) [inline ninja-forms.php]: This will prevent our Admin Notices from firing on any page besides the Dashboard, and on the Dashboard, those notices are being suppressed.

Therefore, this change would remove our ability to post any admin notices.

Revert change or modify the conditions.

File: ninja-forms.php [hunk 2]
```diff
@@ -399,14 +399,15 @@ public function scrub_available_actions( $actions )
...
             // Notices filter and run the notices function.
             $admin_notices = Ninja_Forms()->config( 'AdminNotices' );
             self::$instance->notices->admin_notice( apply_filters( 'nf_admin_notices', $admin_notices ) );
         }
 
         public function plugins_loaded()
         {
-            load_plugin_textdomain( 'ninja-forms', false, basename( dirname( __FILE__ ) ) . '/lang' );
+            // load_plugin_textdomain( 'ninja-forms', false, basename( dirname( __FILE__ ) ) . '/lang' );
```
Comment (Much2tall) [inline ninja-forms.php]: This line is necessary to use our included translation packages.
Revert change.

**Comment by klhall1987** [comment]
Breaks submissions "Terms List" fields.

**Comment by Much2tall** [comment]
"Terms List" does not work properly in develop in either the Submissions table or the Edit submission screen. This PR did not introduce that breakage.

**Comment by Much2tall** [comment]
Regardless of that, I've edited it so that those pages should function properly in the future.
